spring:
  application:
    name: sampick

    datasource:
    url: jdbc:mysql://localhost:3306/sampick?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver
